CREATE TABLE todos (
    Ind INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, 
    Task VARCHAR (250) NOT NULL, 
    Done BOOLEAN NOT NULL,
    CreatedAt TIMESTAMP NOT NULL, 
    CompletedAt TIMESTAMP NOT NULL
);

/* SQL USED TO CREATE THE TABLE */